### ISSUE TITLE
demo broken?

### ISSUE THREAD

**Issue by L72q5** [danhab99/cryptochan#1]
can't post when trying to construct the json manually
this is what i tried:
```
{"author":{"name":"Jtaqu","publickey":"e0aaca02e9fdd424"},"body":{"content":"second","mimetype":"text/plain"},"category":"all","embeds":[],"hash":{"algorithm":"SHA-256","value":"e111f804ea2740211820d015f6a6a86a50508a28b38c968e72bb68839176de13"},"parenthash":"b804da0898e33399dd8cb15776a58c4626185c9b598ce56207e0577e68ce698d","published":"2021-06-28T16:45:21.480Z","signature":"-----BEGIN PGP SIGNATURE-----\n\niHUEABYIAB0WIQTsilfAn0jgQ7sIzP7gqsoC6f3UJAUCYNn8cAAKCRDgqsoC6f3U\nJASIAP0W4i7tZ6aB+fNl1HGsAnycAv1OaGsAfd1XACoVZOFoWgD7BjB2BnF8ZxOv\npsME384Dddc80xAsw4FbVy+I1OAsWAo=\n=srqP\n-----END PGP SIGNATURE-----\n"}
```
gave me an empty 401 json response
my first guess was that it's related to the hashing because while i can verify the signature of 4bxog in "all", i can't verify the hash
iiuc this should have resulted in "b804da0898e33399dd8cb15776a58c4626185c9b598ce56207e0577e68ce698d":
```
~> jq -c '.[] |del(.hash, .__v, .replies, .replyThreads, .approved)' < reply.json | json-stable-stringify | sha256sum
28719295c297db5f7a2004d861710fbba82b1d0434620ace2e8f64edc21854f9  -
```
i then proceeded to try to post via the form with both gnupg- and website-generated keys but neither worked, getting 401s and 404s

**Comment by danhab99** [comment]
Show policy config https://github.com/danhab99/cryptochan#policyts

**Comment by danhab99** [comment]
JSON strings aren't inheritantly good for hashing, especially `JSON.stringify` which is not gaurenteed to return the same string for a given object. Cryptochan uses [`json-stable-stringify`](https://www.npmjs.com/package/json-stable-stringify) to ensure JSON objects are hashable. [See implementation example here](https://github.com/danhab99/cryptochan/blob/main/crypto.ts#L31)

**Comment by danhab99** [comment]
Just looked it up in my DB. I require manual pre-approval for all unidentified public keys on cryptochan.vercel.app because I don't trust people to not post CP or dox people.

You got error code 401 because your key is not approved.

That being said since I have seen your GitHub account I will be able to attribute threads to you, even if you use a single-user key. So I feel safe in approving your public key. Enjoy cryptochan <3
